export * from "./NewPatientDialog";
export * from "./EvolucionDialog";
export * from "./InterconsultaDialog";
export * from "./AntropometriaDialog";
export * from "./HospitalizacionDialog";
export * from "./CloseWithoutSavingDialog";
export * from "./ArchivoAdjuntoDialog";
export * from "./HistoriaMedicaDialog/HistoriaMedicaDialog";
export * from "./EditPacienteDialog";
